seed: 1901
model:
  seq_length: 8
  n_embd: 64
  n_head: 4
  n_layer: 4
  dropout: 0.1


trainer:
  max_epoch: 10
  batch_size: 64
scheduler:
  max_lr: 1e-2

optimizer:
  lr: 1e-3

data:
  path: data/
  train_size: 0.9

wandb:
  project: Fixing Broken R2-D2
  log_freq: 100 # batch

callback:
  patience: 1
  min_delta: 1e-4

checkpoint:
  path: ckpt

