name: testing
on:
  push:
    branches:
    - main
    - master

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.16
      - name: install dep 
        run: |
          python -m pip install --upgrade pip==23.0.1
          python -m pip install -r ./requirements/dev.txt